### ISSUE TITLE
I was just on it like 5 minutes ago now it's not working

### ISSUE THREAD

**Issue by J7DT2023** [NightProxy/Light#2]

**Comment by lucid-devv** [comment]
What link are you using?

**Comment by lucid-devv** [comment]
Nevermind. The URL will be changed soon.

**Comment by J7DT2023** [comment]
this one[ ](https://nightlight.zapto.org/) but umm W site if you guys could keep me updated on when the URL changes that would be nice but keep doing what ur doing cause I had the best time on here (no not like that)
